apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::539812135697:role/eksctl-eksctl-demo2-nodegroup-ng-NodeInstanceRole-DI5ST207CJKP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::539812135697:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-31T21:54:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "88440"
  uid: ac9efe36-ff14-4cf9-b842-159cf558a9ca
